### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Qoja Berim - کجا بریم ؟
email: m.aminwhat@gmail.com
description: اپ کجا بریم؟ - مکان یاب جهت خوشگذرونی و بیرون رفتن
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qojaberim.ir" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: "#efeeff"
twitter_username: m.aminwhat
github_username: aminwhat
author: Amin What
logo: assets/images/large-logo.png
twitter:
  username: m.aminwhat
social:
  name: AminWhat
  links:
    - https://twitter.com/m.aminwhat
    # - https://www.facebook.com/sandoche
    - https://www.linkedin.com/in/sandoche
    # - https://plus.google.com/+SandocheADITTANE
    - https://github.com/aminwhat

languages: ["en"]
ampdir: amp

github: https://github.com/sandoche/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
